// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileBalanceHandler.Models.Data;

namespace MobileBalanceHandler.Migrations
{
    [DbContext(typeof(MobileBalanceContext))]
    partial class MobileBalanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MobileBalanceHandler.Models.Payment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2022, 1, 22, 15, 34, 4, 529, DateTimeKind.Local).AddTicks(4398));

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
